### ISSUE TITLE
Implement policies

### ISSUE THREAD

**Issue by adrienaury** [adrienaury/owl#11]
New local file `policies.yaml`

```yaml
version: v1
policies:
- name: default
  objects:
  - name: unit
    backend: organizationalUnit
    fields:
    - name: id
      backend: ou
    - name: description
      backend: description
  - name: user
    backend: inetOrgPerson
    fields:
    - name: id
      backend: cn
    - name: firstnames
      backend: givenName
      multivalued: true
    - name: lastnames
      backend: sn
      multivalued: true
    - name: emails
      backend: mail
      multivalued: true
    - name: password
      backend: userPassword
  - name: group
    backend: groupOfUniqueNames
    fields:
    - name: id
      backend: cn
    - name: members
      backend: uniqueMember
      multivalued: true
```

Realms use the `default` policy by default, but this can be changed with this command :

``` console
$ owl policy my-policy my-realm
Using policy 'my-policy' for realm 'my-realm'.
```

Or this command if already logged into 'my-realm' :

``` console
$ owl policy my-policy
Using policy 'my-policy' for realm 'my-realm'.
```

The realms.yaml file is updated accordingly :

```yaml
version: v1.beta
realms:
  - id: my-realm
    url: ldap://my-ldap/dc=example,dc=org
    username: cn=admin,dc=example,dc=org
    policy: my-policy
```
